import React from 'react';
import { motion } from 'framer-motion';
import { Calendar, MapPin, Clock, DollarSign, Lock } from 'lucide-react';
import { demoItinerary } from '../lib/demoData';
import { staggerContainer, fadeInUp } from '../lib/motion';

const DemoItinerary = ({ onGetStartedClick }) => {
  const handleGetStarted = () => {
    if (onGetStartedClick) {
      onGetStartedClick();
    } else {
      // Fallback: scroll to top or show alert
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };
  return (
    <section id="demo" className="py-20 bg-black">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          variants={staggerContainer}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <motion.h2 
            variants={fadeInUp}
            className="text-4xl lg:text-5xl font-semibold text-white mb-6"
          >
            See It In Action
          </motion.h2>
          <motion.p 
            variants={fadeInUp}
            className="text-xl text-white/70 max-w-3xl mx-auto mb-8"
          >
            Here's a sample itinerary generated by our AI for a 5-day trip to Tokyo. 
            Sign in to create your own personalized travel plans.
          </motion.p>
          
          {/* Demo Notice */}
          <motion.div
            variants={fadeInUp}
            className="inline-flex items-center space-x-2 bg-yellow-100 text-yellow-800 px-4 py-2 rounded-lg mb-8"
          >
            <Lock size={16} />
            <span className="text-sm font-medium">Demo Mode - Sign in to generate your own</span>
          </motion.div>
        </motion.div>

        {/* Trip Overview */}
        <motion.div
          variants={fadeInUp}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
          className="bg-black rounded-2xl border border-white/10 p-8 mb-12"
        >
          <div className="grid md:grid-cols-4 gap-6">
            <div className="flex items-center space-x-3">
              <div className="bg-white/10 p-3 rounded-lg">
                <MapPin className="text-white" size={24} />
              </div>
              <div>
                <div className="text-sm text-white/60">Destination</div>
                <div className="font-semibold text-white">{demoItinerary.destination}</div>
              </div>
            </div>
            
            <div className="flex items-center space-x-3">
              <div className="bg-white/10 p-3 rounded-lg">
                <Calendar className="text-white" size={24} />
              </div>
              <div>
                <div className="text-sm text-white/60">Duration</div>
                <div className="font-semibold text-white">{demoItinerary.duration} days</div>
              </div>
            </div>
            
            <div className="flex items-center space-x-3">
              <div className="bg-white/10 p-3 rounded-lg">
                <DollarSign className="text-white" size={24} />
              </div>
              <div>
                <div className="text-sm text-white/60">Budget</div>
                <div className="font-semibold text-white">{demoItinerary.budget}</div>
              </div>
            </div>
            
            <div className="flex items-center space-x-3">
              <div className="bg-white/10 p-3 rounded-lg">
                <Clock className="text-white" size={24} />
              </div>
              <div>
                <div className="text-sm text-white/60">Interests</div>
                <div className="font-semibold text-white">{demoItinerary.interests.join(', ')}</div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Itinerary Days */}
        <motion.div
          variants={staggerContainer}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
          className="space-y-8"
        >
          {demoItinerary.itinerary.map((day, index) => (
            <motion.div
              key={index}
              variants={fadeInUp}
              className="bg-black rounded-2xl border border-white/10 overflow-hidden"
            >
              <div className="bg-black p-6 border-b border-white/10">
                <h3 className="text-2xl font-bold text-white">
                  {day.title}
                </h3>
                <p className="text-white/60 mt-2">
                  Day {day.day} of your {demoItinerary.duration}-day adventure
                </p>
              </div>
              
              <div className="p-6">
                <div className="grid gap-4">
                  {day.activities.map((activity, actIndex) => (
                    <motion.div
                      key={actIndex}
                      className="flex items-start space-x-4 p-4 bg-white/5 rounded-lg hover:bg-white/10 transition-colors"
                      whileHover={{ scale: 1.02 }}
                    >
                      <div className="bg-white/10 p-2 rounded-lg flex-shrink-0">
                        <Clock className="text-white" size={20} />
                      </div>
                      <div className="flex-1">
                        <h4 className="font-semibold text-white mb-1">
                          {activity.name}
                        </h4>
                        <p className="text-white/70 text-sm mb-2">
                          {activity.description}
                        </p>
                        {activity.estimated_cost && (
                          <div className="flex items-center space-x-1">
                            <DollarSign className="text-green-600" size={14} />
                            <span className="text-sm text-green-600 font-medium">
                              {activity.estimated_cost}
                            </span>
                          </div>
                        )}
                      </div>
                    </motion.div>
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* CTA */}
        <motion.div
          variants={fadeInUp}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
          className="text-center mt-16"
        >
          <div className="bg-black rounded-2xl p-8 text-white border border-white/10">
            <h3 className="text-3xl font-bold mb-4">Ready to Plan Your Own Adventure?</h3>
            <p className="text-xl text-white/70 mb-8">
              Sign up now and let our AI create a personalized itinerary just for you.
            </p>
            <motion.button
              onClick={handleGetStarted}
              className="bg-white text-black px-8 py-4 rounded-lg font-semibold text-lg hover:bg-white/90 transition-colors"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              Get Started Free
            </motion.button>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default DemoItinerary;
